table restaurant
	lineageTag: 6fc3032b-37b4-4506-bf9d-3c5481e03ee4

	column id
		dataType: int64
		formatString: 0
		lineageTag: 7b7f7540-6833-4ba2-bfc3-3ed5d1ed0682
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 77c490bc-75f2-45fa-9677-10ad6aca8d9f
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 720b0706-1eec-419d-b488-6faf7373adcb
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 0b226922-e0d6-410b-86ab-6e4838ad1cc2
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column rating
		dataType: string
		lineageTag: 25649bab-6021-4afa-8c95-6a1ebd8af230
		summarizeBy: none
		sourceColumn: rating

		annotation SummarizationSetBy = Automatic

	column rating_count
		dataType: string
		lineageTag: bb5f7c61-9f34-4088-87e2-f4bf359068aa
		summarizeBy: none
		sourceColumn: rating_count

		annotation SummarizationSetBy = Automatic

	column cuisine
		dataType: string
		lineageTag: 0da38fbb-6776-488e-9de0-5ccc9f3bc966
		summarizeBy: none
		sourceColumn: cuisine

		annotation SummarizationSetBy = Automatic

	column link
		dataType: string
		lineageTag: 3dccfddd-5fee-465d-b485-c231dca5b79a
		summarizeBy: none
		sourceColumn: link

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: 73748030-55f4-4e33-894b-f91fea981e38
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	partition restaurant = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\UCB\Sem 2\Data warehouse\Datasets\Zomato\restaurant.xlsx"), null, true),
				    restaurant_Sheet = Source{[Item="restaurant",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(restaurant_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"name", type text}, {"Country", type text}, {"city", type text}, {"rating", type any}, {"rating_count", type text}, {"cuisine", type text}, {"link", type text}, {"address", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

